config/routes.rb
Rails.application.routes.draw do
  
    root 'users#new'
  
    #New User
    get 'register' => 'users#new', as: 'new_register'
    get'users/new' => 'users#new'
    #create user
    post 'register' => 'users#create', as: 'register'
    post 'users' => 'users#create'
    #show user
    get 'users/:id' => 'users#show', as: 'user'
    # New Login
    get 'login' => 'logins#new', as:'new_login'
    get 'logins/new' => 'logins#new'
    # Login
    post 'login' => 'logins#create' ,as: 'login'
    post 'logins'  => 'logins#create'
    # Logout   
    delete 'logout' => 'logins#destroy', as: 'logout'
    delete 'logins' => 'logins#destroy' 

    get 'organizations' => 'organizations#index', as: 'organizations'
    post 'organizations' => 'organizations#create', as: 'create_organizations'
    get 'organizations/:id' => 'organizations#show', as: 'organizations_show'
    post 'join_organizations/:id' => 'members#create', as: 'join_organization'
    delete 'leave_organizations/:id' => 'members#destroy', as: 'leave_organization'
  
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user, required: true
  
  has_many :members
  has_many :membering, through: :members, source: :user 

  validates :name, presence: true, length: {minimum: 5}
  validates :description, presence: true, length: {minimum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :organizations
  has_many :members
  has_many :memberers, through: :members, source: :organization 

  email_regex = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/

  before_save :downcase

  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness:true, format: { with: email_regex}

  def downcase
      self.first_name.downcase!
      self.last_name.downcase!
      self.email.downcase!
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
      User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user    
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    def new

    end    

    def create
        user = User.find_by_email(params[:user][:email])

        if user
            if user.try(:authenticate, params[:user][:password])
                session[:user_id] = user.id

                return redirect_to organizations_path

            end

            flash[:errors] = ['Password is not correct.']
        else
            flash[:errors] = ['Account not found, please register first.']   
        end
        
        return redirect_to :back
    end
    
    def destroy
        session.delete(:user_id) if session[:user_id]
        return redirect_to new_login_path
    end    

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
        
    def create
        organization = Organization.find(params[:member][:organization_id])
        Member.create(member_params) unless organization.members.include? current_user

        return redirect_to organizations_path
    end

    def destroy
        @organization = Organization.find(params[:id])
        
        @organization.destroy
 
        return redirect_to organizations_path
    end 
        
    private
        def member_params
            params.require(:member).permit(:organization_id).merge(user: current_user)
        end    

end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
def index
    @organization = Organization.all

end

def create
    @organization = Organization.create(organization_params)
    
    if @organization.valid?
        Member.create(user: current_user, organization: @organization)
        
        return redirect_to organizations_path
    end       

    flash[:errors] = @organization.errors.full_messages

    return redirect_to :back
end
def show
    @organization = Organization.find(params[:id])
    
end 
private
    def organization_params
        params.require(:organization).permit(:name, :description).merge(user:current_user)

    end    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new

    end
    
    def create
        user = User.create(user_params)

        if user.valid?
            session[:user_id] = user.id

            return redirect_to organizations_path
        end
        
        flash[:errors] = user.errors.full_messages
        return redirect_to :back
    end
    
    def show
        @user = User.find(session[:user_id])
    end 
    
    private
        def user_params
           params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation) 
        end    
end
        

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organization/Members</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" i           integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"     integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="<%= root_path %>">Organizations/Members</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if current_user %> 
                <li class="nav-item active">
                  <a class="nav-link" href="<%= logout_path %>" data-method="delete">Logout</a>
                </li>
            <% else %>
                <li class="nav-item">
                  <a class="nav-link" href="<%= new_register_path %>">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<%= new_login_path %>">Login</a>
                </li>
            <% end %>
          </ul>
         </div>
      </nav> 
        <% if flash[:errors] %>
            <% flash[:errors].each do |error| %>
              <p class="text-danger"><%= error %> </p>
            <% end %>
        <% end %>       

      <%= yield %> 
            
    </div>    
    
  </body>
</html>

app/views/logins/new.html.erb
<div class="row">
<div class="col-md-12">
    <h2>Login</h2> 
</div>    
</div>


<div class ="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    <form action="<%= login_path %>" method="post" class="form">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>"/>
        <div class="form-group">                
            <input type="email" name= "user[email]" class="form-control" id="email" placeholder="Email">              
        </div>
        <div class="form-group">                
            <input type="password" name= "user[password]" class="form-control" id="password" placeholder="Password">
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Login</button>
        </div>
    </form>
</div>
<div class="col-md-2"></div>
</div>

app/views/organizations/index.html.erb
<p>Hi,  <%= current_user.first_name.capitalize %>!</p>
Here are the organizations you may join:

    <% @organization.each do |organization| %>
        <p><a href="<%= organizations_show_path organization.id%>"><%= organization.name %></a></p>
        <p><%= organization.membering.count %></p>
        <p><%= organization.description %></p>
    <% end %>

<h5>Create a new Organization:</h5>

<div class ="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <form action="<%= create_organizations_path %>" method="post" class="form">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>"/>
            <div class="form-group">
                <input type="text" name= "organization[name]" class="form-control" id="name" placeholder="Name">                
            </div>
            <div class="form-group">                
                <input type="text" name= "organization[description]" class="form-control" id="description" placeholder="Description">
            </div>
            <div class="form-group">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </form>
    </div>
    <div class="col-md-2"></div>
</div>

app/views/organizations/show.html.erb

<a class="nav-link" href="<%= organizations_path %>">Dashboard</a>

<p><%= @organization.name %></p>
<p><%= @organization.description%></p>


<% if @organization.membering.include? current_user  %>
    <form action="<%= leave_organization_path %>" method= "post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>"/>
        <input type="hidden" name="member[organization_id]" value="<%= @organization.id  %>"/>
        <input type="hidden" name="_method" value="delete"/>
        <button class="btn btn-sm btn-warning" type="submit">Leave</button>
    </form>
<% else %>
    <form action="<%= join_organization_path %>" method= "post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>"/>
        <input type="hidden" name="member[organization_id]" value="<%= @organization.id  %>"/>
        <button class="btn btn-sm btn-primary" type="submit">Join</button>
    </form>
<% end %>  
<% @organization.membering.each do |user| %>
    <% if user != @organization.user %>
        <p><%= user.first_name %></p>
     <% end %>    
<% end %>

app/views/users/new.html.erb
<div class="row">
<div class="col-md-12">
    <h2>Register</h2> 
</div>    
</div>


<div class ="row">
<div class="col-md-2"></div>
<div class="col-md-8">
    <form action="<%= register_path %>" method="post" class="form">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>"/>
        <div class="form-group">
            <input type="text" name= "user[first_name]" class="form-control" id="first_name" placeholder="First Name">                
        </div>
        <div class="form-group">                
            <input type="text" name= "user[last_name]" class="form-control" id="last_name" placeholder="Last Name">
        </div>
        <div class="form-group">                
            <input type="email" name= "user[email]" class="form-control" id="email" placeholder="Email">              
        </div>
        <div class="form-group">                
            <input type="password" name= "user[password]" class="form-control" id="password" placeholder="Password">
        </div>
        <div class="form-group">                
            <input type="password" name= "user[password_confirmation]"class="form-control" id="password_confirmation" placeholder="Password Confirmation">               
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">Register</button>
        </div>
    </form>
</div>
<div class="col-md-2"></div>
</div>


app/views/users/show.html.erb
<h3>Show page</h3>

<p>First Name: <%= @user.first_name %> </p>